Extend template loading to 24 attempts and a total of ~2 minutes

diff --git a/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load b/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
--- a/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
+++ b/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
@@ -50,7 +50,7 @@ if [ ! -f /opt/so/state/estemplates.txt ]; then
     for i in *; do 
       TEMPLATE=$(echo $i | cut -d '.' -f1) 
       echo "$TEMPLATE-mappings" 
-      retry 5 5 "so-elasticsearch-query _component_template/${TEMPLATE}-mappings -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE-mappings"
+      retry 24 5 "so-elasticsearch-query _component_template/${TEMPLATE}-mappings -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE-mappings"
     done
     echo
 
@@ -65,7 +65,7 @@ if [ ! -f /opt/so/state/estemplates.txt ]; then
     for i in $component_pattern; do 
       TEMPLATE=${i::-5} 
       echo "$TEMPLATE"
-      retry 5 5 "so-elasticsearch-query _component_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"
+      retry 24 5 "so-elasticsearch-query _component_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"
     done
     echo
 	    
@@ -76,7 +76,7 @@ if [ ! -f /opt/so/state/estemplates.txt ]; then
     for i in *; do 
       TEMPLATE=$(echo $i | cut -d '.' -f1); 
       echo "$TEMPLATE"
-      retry 5 5 "so-elasticsearch-query _component_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"  
+      retry 24 5 "so-elasticsearch-query _component_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"  
     done
     echo
 
@@ -93,7 +93,7 @@ if [ ! -f /opt/so/state/estemplates.txt ]; then
     for i in $pattern; do
       TEMPLATE=${i::-14}
       echo "$TEMPLATE"
-      retry 5 5 "so-elasticsearch-query _index_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"     
+      retry 24 5 "so-elasticsearch-query _index_template/$TEMPLATE -d@$i -XPUT | grep '{\"acknowledged\":true}'" || fail "Could not load template: $TEMPLATE"     
       done
   else
     {% if GLOBALS.role == 'so-heavynode' %}
