Add back check for initial state file and prep

diff --git a/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load b/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
--- a/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
+++ b/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-templates-load
@@ -13,8 +13,7 @@ if [[ -f $STATE_FILE_INITIAL ]]; then
   # The initial template load has already run. As this is a subsequent load, all dependencies should 
   # already be satisified. Therefore, immediately exit/abort this script upon any template load failure
   # since this is an unrecoverable failure.
-  # should_exit_on_failure=1
-  :
+  should_exit_on_failure=1
 else
   # This is the initial template load, and there likely are some components not yet setup in Elasticsearch.
   # Therefore load as many templates as possible at this time and if an error occurs proceed to the next 
@@ -25,7 +24,7 @@ else
 fi
 
 # If soup is running, ignore errors
-ps aux | grep -v grep | grep soup > /dev/null && should_exit_on_failure=0
+pgrep soup > /dev/null && should_exit_on_failure=0
 
 load_failures=0
 
@@ -34,16 +33,14 @@ load_template() {
   file=$2
 
   echo "Loading template file $i" 
-  #if ! retry 3 5 "
-  so-elasticsearch-query $uri -d@$file -XPUT 
-  #"{\"acknowledged\":true}"; then
-  #  if [[ $should_exit_on_failure -eq 1 ]]; then
-  #    fail "Could not load template file: $file"
-  #  else
-  #    load_failures=$((load_failures+1))
-  #    echo "Incremented load failure counter: $load_failures"
-  #  fi
-  #fi
+  if ! retry 3 5 "so-elasticsearch-query $uri -d@$file -XPUT" "{\"acknowledged\":true}"; then
+    if [[ $should_exit_on_failure -eq 1 ]]; then
+      fail "Could not load template file: $file"
+    else
+      load_failures=$((load_failures+1))
+      echo "Incremented load failure counter: $load_failures"
+    fi
+  fi
 }
 
 if [ ! -f $STATE_FILE_SUCCESS ]; then
