start cron and enable highstate if soup exits on error

diff --git a/salt/common/tools/sbin/so-common b/salt/common/tools/sbin/so-common
--- a/salt/common/tools/sbin/so-common
+++ b/salt/common/tools/sbin/so-common
@@ -407,11 +407,16 @@ set_version() {
 
 systemctl_func() {
 	local action=$1
+	local echo_action=$1
 	local service_name=$2
 
+	if [[ "$echo_action" == "stop" ]]; then
+		$echo_action = "stopp"
+	fi
+
 	echo ""
-	echo "${action^}ing $service_name service at $(date +"%T.%6N")"
-    systemctl $action $service_name
+	echo "${echo_action^}ing $service_name service at $(date +"%T.%6N")"
+    systemctl $action $service_name && echo "Successfully ${echo_action}ed $service_name." || echo "Failed to $action $service_name."
 	echo ""
 }
 
