ensure salt-master service is running before proceeding with soup

diff --git a/salt/common/tools/sbin/so-common b/salt/common/tools/sbin/so-common
--- a/salt/common/tools/sbin/so-common
+++ b/salt/common/tools/sbin/so-common
@@ -120,6 +120,30 @@ check_elastic_license() {
 	fi  
 }
 
+check_salt_master_status() {
+	local timeout=$1
+	echo "Checking if we can talk to the salt master"
+	salt-call state.show_top -t $timeout concurrent=true
+
+	return
+}
+
+check_salt_minion_status() {
+	local timeout=$1
+	echo "Checking if the salt minion will respond to jobs" >> "$setup_log" 2>&1
+	salt "$MINION_ID" test.ping -t $timeout > /dev/null 2>&1
+	local status=$?
+	if [ $status -gt 0 ]; then
+		echo "  Minion did not respond" >> "$setup_log" 2>&1
+	else
+		echo "  Received job response from salt minion" >> "$setup_log" 2>&1
+	fi
+
+	retrun $status
+}
+
+
+
 copy_new_files() {
   # Copy new files over to the salt dir
   cd $UPDATE_DIR
diff --git a/salt/common/tools/sbin/soup b/salt/common/tools/sbin/soup
--- a/salt/common/tools/sbin/soup
+++ b/salt/common/tools/sbin/soup
@@ -1018,6 +1018,12 @@ main() {
   echo ""
   require_manager
 
+  if ! check_salt_master_status -t 30; then
+  	echo "Could not talk to salt master"
+    echo "Please run `systemctl status salt-master` to ensure the salt-master service is running."
+    exit 1
+  fi
+
   check_pillar_items
 
   echo "Checking to see if this is an airgap install."
