Fix backwards logic

diff --git a/salt/common/tools/sbin/so-common b/salt/common/tools/sbin/so-common
--- a/salt/common/tools/sbin/so-common
+++ b/salt/common/tools/sbin/so-common
@@ -341,7 +341,7 @@ run_check_net_err() {
 	
 	if [[ $exit_code -ne 0 ]]; then
 		ERR_HANDLED=true
-		[[ -z $no_retry ]] && echo "Command failed with error $exit_code"
+		[[ -z $no_retry ]] || echo "Command failed with error $exit_code"
 		echo "$err_msg"
 		exit $exit_code
 	fi
