more logging for influxdb migration

diff --git a/salt/common/tools/sbin/soup b/salt/common/tools/sbin/soup
--- a/salt/common/tools/sbin/soup
+++ b/salt/common/tools/sbin/soup
@@ -313,7 +313,7 @@ post_2.3.5X_to_2.3.60() {
   echo "The status can be checked in $INFLUXDB_MIGRATION_LOG"
   read -p "Press enter to continue."
   echo ""
-  docker exec -dt so-influxdb /bin/bash -c 'influx -ssl -unsafeSsl -database telegraf -execute "SELECT mean(*) INTO "so_long_term".:MEASUREMENT FROM /.*/ GROUP BY time(5m),*"' >> "$INFLUXDB_MIGRATION_LOG" 2>&1
+  docker exec -dt so-influxdb /bin/bash -c 'influx -ssl -unsafeSsl -database telegraf -execute "SELECT mean(*) INTO "so_long_term".:MEASUREMENT FROM /.*/ GROUP BY time(5m),*" && echo "InfluxDB migration complete." || echo "InfluxDB migration failed."' >> "$INFLUXDB_MIGRATION_LOG" 2>&1
 
   POSTVERSION=2.3.60
 }
