Try to fix bash trap

diff --git a/salt/common/tools/sbin/soup b/salt/common/tools/sbin/soup
--- a/salt/common/tools/sbin/soup
+++ b/salt/common/tools/sbin/soup
@@ -28,13 +28,12 @@ WHATWOULDYOUSAYYAHDOHERE=soup
 
 set -e
 
-trap 'check_err $? $BASH_LINENO $BASH_COMMAND' EXIT
+trap 'check_err $? $BASH_LINENO' EXIT
 
 check_err() {
   local exit_code=$1
   local lineno=$2
-  local cmd=$3
-  local err_msg="Unknown error occured, please check $SOUP_LOG for details."
+  local err_msg="Unhandled error occured, please check $SOUP_LOG for details."
 
   if [[ $exit_code -ne 0 ]]; then
     printf '%s' "Soup failed on line $lineno with error $exit_code: "
@@ -86,7 +85,7 @@ check_err() {
         echo 'No route to host'
       ;;
       *)
-        echo ''
+        echo 'Unhandled error'
         echo "$err_msg"
       ;;
     esac
