uninstall agent on final failed attempt

diff --git a/salt/elasticfleet/tools/sbin/so-elastic-agent-install b/salt/elasticfleet/tools/sbin/so-elastic-agent-install
--- a/salt/elasticfleet/tools/sbin/so-elastic-agent-install
+++ b/salt/elasticfleet/tools/sbin/so-elastic-agent-install
@@ -27,9 +27,13 @@ check_agent_health() {
     return 1
 }
 
-if command -v elastic-agent >/dev/null 2>&1; then
-    elastic-agent uninstall -f
-fi
+uninstall_agent() {
+    if command -v elastic-agent >/dev/null 2>&1; then
+        elastic-agent uninstall -f
+    fi
+}
+
+uninstall_agent
 
 if [[ -z "$GRIDNODETOKEN" ]]; then
     noderole=$(so-yaml.py get -r /etc/salt/grains role)
@@ -38,6 +42,12 @@ if [[ -z "$GRIDNODETOKEN" ]]; then
     else
         GRIDNODETOKEN=$(salt-call pillar.get global:fleet_grid_enrollment_token_general --out=newline_values_only)
     fi
+fi
+
+if [[ -z "$GRIDNODETOKEN" ]]; then
+    echo "Unable to determine Elastic Fleet enrollment token. Exiting."
+
+    exit 1
 fi
 
 if [[ ! -x /opt/so/so-elastic-agent_linux_amd64 ]]; then
@@ -50,7 +60,7 @@ if [[ -x /opt/so/so-elastic-agent_linux_amd64 ]]; then
     cd /opt/so/ || exit 1
 
     while [[ $attempts -lt 3 ]]; do
-        if ./so-elastic-agent_linux_amd64 -token="$GRIDNODETOKEN" -force; echo "Verifying Elastic Agent health..." && check_agent_health; then
+        if ./so-elastic-agent_linux_amd64 -token="$GRIDNODETOKEN" -force && echo "Verifying Elastic Agent health..." && check_agent_health; then
             rm -f /opt/so/so-elastic-agent_linux_amd64
             elastic-agent status
 
@@ -65,6 +75,8 @@ if [[ -x /opt/so/so-elastic-agent_linux_amd64 ]]; then
         fi
     done
 
+    uninstall_agent
+    rm -f /opt/so/so-elastic-agent_linux_amd64
     echo "The so-elastic-agent installer failed after 3 attempts. Exiting."
 
     exit 1
