fix if and indent

diff --git a/salt/manager/tools/sbin/soup b/salt/manager/tools/sbin/soup
--- a/salt/manager/tools/sbin/soup
+++ b/salt/manager/tools/sbin/soup
@@ -308,7 +308,7 @@ clone_to_tmp() {
 phases_pillar_2_4_70() {
   echo "Checking if pillar value: elasticsearch.index_settings.global_overrides.index_template.phases exists"
   pv=$(salt-call pillar.get elasticsearch:index_settings:global_overrides:index_template:phases --out=newline_values_only -lquiet)
-  if [ $? - eq 0 ]; then
+  if [ $? -eq 0 ]; then
     if [ ! -z "${pv}" ]; then
       echo "Found elasticsearch.index_settings.global_overrides.index_template.phases set to:"
       echo "${pv}"
@@ -987,7 +987,7 @@ apply_hotfix() {
   elif [[ "$INSTALLEDVERSION" == "2.4.70" ]] ; then
     phases_pillar_2_4_70
   else
-   echo "No actions required. ($INSTALLEDVERSION/$HOTFIXVERSION)"
+    echo "No actions required. ($INSTALLEDVERSION/$HOTFIXVERSION)"
   fi
 }
 
