remove pillar if exists

diff --git a/salt/manager/tools/sbin/soup b/salt/manager/tools/sbin/soup
--- a/salt/manager/tools/sbin/soup
+++ b/salt/manager/tools/sbin/soup
@@ -305,6 +305,25 @@ clone_to_tmp() {
   fi
 }
 
+elasticsearch_pillar_2_4_70() {
+  echo "Checking if pillar value: elasticsearch.index_settings.global_overrides.index_template.phases exists"
+  pv=$(salt-call pillar.get elasticsearch:index_settings:global_overrides:index_template:phases --out=newline_values_only -lquiet)
+  if [ $? - eq 0 ]; then
+    if [ ! -z "${pv}" ]; then
+      echo "Found elasticsearch.index_settings.global_overrides.index_template.phases set to:"
+      echo "${pv}"
+      echo "A backup of all pillars was saved to /nsm/backup/"
+      echo "Removing unused pillar value: elasticsearch.index_settings.global_overrides.index_template.phases"
+      echo "If you want to set policies, navigate to the SOC Grid Configuration UI at elasticsearch.index_settings.global_overrides.policy.phases"
+      so-yaml.py remove /opt/so/saltstack/local/pillar/elasticsearch/soc_elasticsearch.sls elasticsearch.index_settings.global_overrides.index_template.phases
+      so-yaml.py remove /opt/so/saltstack/local/pillar/elasticsearch/adv_elasticsearch.sls elasticsearch.index_settings.global_overrides.index_template.phases
+    else
+      echo "Pillar elasticsearch.index_settings.global_overrides.index_template.phases does not exist. There is nothing to do for this hotfix."
+    fi
+      fail "Could not query pillar. Ensure salt-master and salt-minion are running properly. The hotfix was not applied"
+  fi
+}
+
 enable_highstate() {
     echo "Enabling highstate."
     salt-call state.enable highstate -l info --local
@@ -592,6 +611,7 @@ up_to_2.4.70() {
   suricata_idstools_migration
   toggle_telemetry
   add_detection_test_pillars
+  elasticsearch_pillar_2_4_70
   INSTALLEDVERSION=2.4.70
 }
 
@@ -962,12 +982,13 @@ apply_hotfix() {
       mv /etc/pki/managerssl.key /etc/pki/managerssl.key.old
       systemctl_func "start" "salt-minion"
       (wait_for_salt_minion "$MINIONID" "5" '/dev/stdout' || fail "Salt minion was not running or ready.") 2>&1 | tee -a "$SOUP_LOG"
-    fi  
+    fi
+  elif [[ "$INSTALLEDVERSION" == "2.4.70" ]] ; then
+    elasticsearch_pillar_2_4_70
   else
    echo "No actions required. ($INSTALLEDVERSION/$HOTFIXVERSION)"
   fi
 }
-
 
 #upgrade salt to 3004.1
 #2_3_10_hotfix_1() {
